#!/usr/bin/env node
// Slice A: turn a deck's question/answer cards into multiple-choice items.
// Writer, then Distractor, then Critic, per question. See
// specs/agents/spec.md §4 for the contract this satisfies.
//
//   npm run quiz -- --deck interview-prep [--only 1.1,1.2] [--force] [--stub]
//
// Writes data/quiz/<deck-id>.yaml and nothing else. It never commits and never
// deploys: read the diff, then publish with scripts/publish.sh as usual.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import * as yaml from "js-yaml";

import { askJson, AgentError, dialMode } from "../lib/dial.mjs";
import {
  validateWriterReply,
  validateDistractorReply,
  validateCriticReply,
  validateQuizItem,
} from "../agents/schemas.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const dataDir = path.join(root, "data");
const agentsDir = path.join(root, "agents");

const HEADER = `# Generated by scripts/generate-quiz.mjs. Review this diff before publishing.
# Source of truth for the questions themselves is data/<deck>.yaml.
`;

const WRITER_ROUNDS = 2; // one attempt, plus one rewrite from the Critic's notes

// --------------------------------------------------------------- deck access

function loadDeck(deckId) {
  const files = readdirSync(dataDir).filter((f) => f.endsWith(".yaml") || f.endsWith(".yml"));
  for (const file of files) {
    const deck = yaml.load(readFileSync(path.join(dataDir, file), "utf8"));
    if (deck?.id === deckId) return deck;
  }
  const ids = files
    .map((f) => yaml.load(readFileSync(path.join(dataDir, f), "utf8"))?.id)
    .filter(Boolean);
  throw new Error(`no deck with id "${deckId}" in data/. Available: ${ids.join(", ") || "none"}`);
}

function deckQuestions(deck) {
  const out = [];
  for (const sec of deck.sections ?? []) {
    for (const tier of sec.tiers ?? []) {
      for (const q of tier.questions ?? []) out.push(q);
    }
  }
  return out;
}

// ------------------------------------------------------------------- the run

const prompts = new Map();
function prompt(name) {
  if (!prompts.has(name)) {
    prompts.set(name, readFileSync(path.join(agentsDir, `${name}.md`), "utf8"));
  }
  return prompts.get(name);
}

// Rotating by a hash of the question id keeps the correct answer off position 1
// without making the file churn: the same id always lands in the same place, so
// a re-run produces a byte-identical file.
function placeOptions(id, correct, distractors) {
  const options = [{ ...correct, correct: true }, ...distractors];
  let hash = 0;
  for (const ch of String(id)) hash = (hash * 31 + ch.charCodeAt(0)) % 9973;
  const shift = hash % options.length;
  return [...options.slice(shift), ...options.slice(0, shift)];
}

async function buildItem(question, { log }) {
  const source = {
    id: question.id,
    question: question.question,
    lead: question.lead,
    body: question.body ?? "",
  };
  let notes = [];

  for (let round = 1; round <= WRITER_ROUNDS; round++) {
    const rejection = notes.length
      ? `\n\nA previous attempt was rejected:\n${notes.map((n) => `- ${n}`).join("\n")}`
      : "";

    const written = await askJson({
      agent: "writer",
      system: prompt("writer"),
      user: JSON.stringify(source) + rejection,
      validate: validateWriterReply,
    });

    const distracted = await askJson({
      agent: "distractor",
      system: prompt("distractor"),
      user: JSON.stringify({ ...source, correct: written.correct }) + rejection,
      validate: validateDistractorReply,
    });

    const item = {
      question_id: question.id,
      stem: written.stem,
      options: placeOptions(question.id, written.correct, distracted.options),
    };

    // Cheap local check first: no point paying for a Critic call on something
    // already malformed.
    const shapeProblems = validateQuizItem(item);
    if (shapeProblems.length) {
      notes = shapeProblems;
      log(`  round ${round}: malformed, ${shapeProblems[0]}`);
      continue;
    }

    const verdict = await askJson({
      agent: "critic",
      system: prompt("critic"),
      user: JSON.stringify({ id: question.id, item, source }),
      validate: validateCriticReply,
    });

    if (verdict.ok) return { item, rounds: round };

    notes = verdict.problems;
    log(`  round ${round}: critic rejected, ${verdict.problems[0]}`);
  }

  return { item: null, rounds: WRITER_ROUNDS, problems: notes };
}

// ------------------------------------------------------------------ the file

function readQuizFile(file) {
  if (!existsSync(file)) return { items: [] };
  const parsed = yaml.load(readFileSync(file, "utf8"));
  return { items: Array.isArray(parsed?.items) ? parsed.items : [] };
}

function serialize(deckId, items) {
  return HEADER + yaml.dump({ deck: deckId, items }, { lineWidth: 88, noRefs: true });
}

export async function generateQuiz({
  deckId,
  only = null,
  force = false,
  quizFile = null,
  log = console.log,
} = {}) {
  const deck = loadDeck(deckId);
  const questions = deckQuestions(deck);
  const file = quizFile ?? path.join(dataDir, "quiz", `${deckId}.yaml`);

  const existing = new Map(readQuizFile(file).items.map((item) => [item.question_id, item]));
  const wanted = only ? new Set(only) : null;

  if (wanted) {
    const known = new Set(questions.map((q) => String(q.id)));
    const unknown = [...wanted].filter((id) => !known.has(id));
    if (unknown.length) throw new Error(`--only names ids not in "${deckId}": ${unknown.join(", ")}`);
  }

  const targets = questions.filter((q) => {
    if (wanted && !wanted.has(String(q.id))) return false;
    return force || !existing.has(q.id);
  });

  const summary = { generated: 0, skipped: [], unchanged: existing.size };

  for (const question of targets) {
    log(`→ ${question.id} ${String(question.question).slice(0, 60)}…`);
    try {
      const { item, problems } = await buildItem(question, { log });
      if (!item) {
        summary.skipped.push({ id: question.id, reason: problems?.[0] ?? "rejected by the critic" });
        log(`  skipped after ${WRITER_ROUNDS} rounds`);
        continue;
      }
      if (existing.has(question.id)) summary.unchanged--;
      existing.set(question.id, item);
      summary.generated++;
      log(`  ok`);
    } catch (e) {
      // An agent that will not return valid JSON is this question's problem,
      // not the run's. Record it and move on, exactly as a critic rejection does.
      const reason = e instanceof AgentError ? e.message : `${e.name}: ${e.message}`;
      summary.skipped.push({ id: question.id, reason });
      log(`  skipped: ${reason}`);
    }
  }

  // Written back in deck order, so the file reads top to bottom like the site.
  const ordered = questions.map((q) => existing.get(q.id)).filter(Boolean);
  const next = serialize(deckId, ordered);
  const current = existsSync(file) ? readFileSync(file, "utf8") : null;

  if (next !== current) {
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, next, "utf8");
    summary.written = true;
  } else {
    summary.written = false;
  }

  summary.total = ordered.length;
  summary.file = file;
  return summary;
}

// ---------------------------------------------------------------------- cli

function parseArgs(argv) {
  const args = { deckId: null, only: null, force: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--deck") args.deckId = argv[++i];
    else if (arg === "--only") args.only = argv[++i]?.split(",").map((s) => s.trim()).filter(Boolean);
    else if (arg === "--force") args.force = true;
    else if (arg === "--stub") process.env.DIAL_STUB = "1";
    else if (arg.startsWith("--stub=")) process.env.DIAL_STUB = arg.slice("--stub=".length);
    else throw new Error(`unknown argument "${arg}"`);
  }
  if (!args.deckId) throw new Error("--deck <id> is required");
  return args;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const args = parseArgs(process.argv.slice(2));
    const { mode, scenario } = dialMode();
    if (mode === "stub") {
      console.log(`! stub mode (${scenario}): replies are canned, every string is marked [stub]\n`);
    }

    const summary = await generateQuiz(args);

    console.log(`\ngenerated ${summary.generated}, unchanged ${summary.unchanged}, skipped ${summary.skipped.length}`);
    for (const skip of summary.skipped) console.log(`  ✗ ${skip.id}: ${skip.reason}`);
    console.log(
      summary.written
        ? `✓ ${path.relative(root, summary.file)} now holds ${summary.total} item(s)`
        : `= ${path.relative(root, summary.file)} unchanged`
    );
  } catch (e) {
    console.error(`✗ ${e.message}`);
    process.exit(1);
  }
}
